// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: feedsUser.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const feedsUser = `-- name: FeedsUser :one
SELECT id, created_at, updated_at, name FROM users
WHERE ID = $1
`

func (q *Queries) FeedsUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, feedsUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}
